version: '3.9'
services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./session:/root/.wwebjs_auth  # Persistir sessões do WhatsApp
    restart: unless-stopped