version: '3.9'
services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./whatsapp_sessions:/usr/src/app/whatsapp_sessions  # Persistir o diretório de sessões
    restart: unless-stopped